version: 2

jobs:
  build:
    docker:
       - image: docker.palantir.build/circle2-build-images/ubuntu-jdk-npm:0.19.0
    working_directory: ~/project
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build images
          command: ./build.sh
      - run:
          name: push base images
          command: ./publish.sh
